# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_cartitem_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='notes',
        ),
    ]
