# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170610_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='factura_url',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
